<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WILASSETA0041.local" failures="1" tests="9" name="com.automation.tests.prmsTestScript" time="195.160" errors="0" timestamp="26 May 2023 14:18:37 GMT" skipped="8">
  <testcase classname="com.automation.tests.prmsTestScript" name="verifyUpdateDetailsOfTickets" time="195.160">
    <failure message="expected [9] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [9] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.automation.tests.prmsTestScript.verifyUpdateDetailsOfTickets(prmsTestScript.java:388)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyUpdateDetailsOfTickets -->
  <testcase classname="com.automation.tests.prmsTestScript" name="verifyCreateIssueFromBacklogFunctionality">
    <skipped/>
  </testcase> <!-- verifyCreateIssueFromBacklogFunctionality -->
  <testcase classname="com.automation.tests.prmsTestScript" name="verifyCreateSprintFunctionality">
    <skipped/>
  </testcase> <!-- verifyCreateSprintFunctionality -->
  <testcase classname="com.automation.tests.prmsTestScript" name="verifyCreateNewProject">
    <skipped/>
  </testcase> <!-- verifyCreateNewProject -->
  <testcase classname="com.automation.tests.prmsTestScript" name="verifyAddMemberFunctionalityFromBoard">
    <skipped/>
  </testcase> <!-- verifyAddMemberFunctionalityFromBoard -->
  <testcase classname="com.automation.tests.prmsTestScript" name="verifyCreateTeamBoard">
    <skipped/>
  </testcase> <!-- verifyCreateTeamBoard -->
  <testcase classname="com.automation.tests.prmsTestScript" name="verifyCreateIssueFromBoard">
    <skipped/>
  </testcase> <!-- verifyCreateIssueFromBoard -->
  <testcase classname="com.automation.tests.prmsTestScript" name="verifySprintActivation">
    <skipped/>
  </testcase> <!-- verifySprintActivation -->
  <testcase classname="com.automation.tests.prmsTestScript" name="verifyAddMemberFromProjectSetting">
    <skipped/>
  </testcase> <!-- verifyAddMemberFromProjectSetting -->
</testsuite> <!-- com.automation.tests.prmsTestScript -->
